### ISSUE TITLE
difference in your res101.pth and pytorch's provided https://s3.amazonaws.com/pytorch/models/resnet101-5d3b4d8f.pth

### ISSUE THREAD

**Issue by Feynman27** [ruotianluo/pytorch-faster-rcnn#19]
What's the difference between the imagenet resnet 101 model you provide (https://github.com/ruotianluo/pytorch-resnet) and that provided by pytorch at  https://s3.amazonaws.com/pytorch/models/resnet101-5d3b4d8f.pth? You note that the two models are different. Can you give a brief summary how?

**Comment by ruotianluo** [comment]
So, first of all, the torchvision resnet has a different configurations of network.(Some small differences, but will totally fail if using the same weights) Secondly, the resnet101 used in the repository assumes normalized 0-255 images input. So you get nan mainly because the scale of input is too different.
